&nbsp<a href="<?php $sess->purl("/phplib/EventLog.php") ?>" class=toplink>Event Log</a>&nbsp;&nbsp
&nbsp<a href="<?php $sess->purl("/phplib/devices.php") ?>" class=toplink>Devices</a>&nbsp;&nbsp
&nbsp<a href="<?php $sess->purl("/phplib/login_types.php") ?>" class=toplink>Login Types</a>&nbsp;&nbsp
&nbsp<a href="<?php $sess->purl("/phplib/menu.php") ?>" class=toplink>Menu</a>&nbsp;&nbsp
&nbsp<a href="<?php $sess->purl("/phplib/sections.php") ?>" class=toplink>Sections</a>&nbsp;&nbsp
